# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.46440757 0.10689484 0.0876995 ]
  [0.15839606 0.56351954 0.45315917]
  [0.11805476 0.94651805 0.02556332]]

 [[0.02390126 0.86705914 0.95531959]
  [0.40560081 0.34007641 0.5926376 ]
  [0.93901051 0.08310202 0.52849436]]

 [[0.62142745 0.77129407 0.76529674]
  [0.50416016 0.40204946 0.72962365]
  [0.34533072 0.47001508 0.40685865]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)




Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.29317724 0.15660357 0.39157017 0.16118974 0.70941013]
 [0.61910144 0.05633425 0.09985301 0.64554805 0.14311884]
 [0.3287275  0.59725081 0.9129135  0.55958138 0.85721105]
 [0.39982253 0.92661249 0.64657904 0.93453579 0.87722381]
 [0.35922308 0.91708329 0.34666338 0.59758061 0.59085303]]
After normalization:
[[0.26969094 0.11417575 0.38173006 0.11939798 0.74365149]
 [0.64081782 0.         0.04955441 0.67093233 0.09882082]
 [0.31017168 0.6159367  0.9753789  0.57304287 0.91195104]
 [0.39112694 0.99097782 0.6721063  1.         0.93473938]
 [0.34489672 0.980127   0.33059511 0.61631224 0.60865162]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 0 0]
Second array:
[0 0 1 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.24251528 0.27378118 0.83472536 0.84111453 0.04248385 0.75224684
 0.18147776 0.26887751 0.30979267 0.11316549]
Maximum value replaced by 0:
[0.24251528 0.27378118 0.83472536 0.         0.04248385 0.75224684
 0.18147776 0.26887751 0.30979267 0.11316549]


# 9. How to print all the values of an array?

There are 3 ways of how the printing of arrays can be done:

1.Using for loop :
2.Convert a list to a string for display :
3.Using map :

In [13]:
#1.Using for loop:

a = [1, 2, 3, 4, 5] 

for x in range(len(a)): 
    print(a[x])

1
2
3
4
5


In [15]:
#2.Convert a list to a string for display :

a =["Geeks", "for", "Geeks"] 

print(' '.join(a)) 

a = [1, 2, 3, 4, 5] 
  
print(str(a)[1:-1])



Geeks for Geeks
1, 2, 3, 4, 5


In [17]:
#Using map:

a = [1, 2, 3, 4, 5] 
print(' '.join(map(str, a)))  
  
print("in new line")
print('\n'.join(map(str, a))) 

1 2 3 4 5
in new line
1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.69161795 0.46150463 0.83665197 0.43455681 0.64799999 0.74317031
  0.86261727 0.49172637 0.5944441  0.60814499]
 [0.6583999  0.81251263 0.83000769 0.15494899 0.27247479 0.26022337
  0.12103123 0.35031208 0.77257361 0.76042537]
 [0.5121304  0.41381754 0.32049788 0.25338887 0.98323719 0.27412414
  0.06157086 0.59191664 0.73429419 0.97893474]
 [0.62214355 0.8951362  0.78308691 0.59924413 0.59317881 0.90302173
  0.8270325  0.22174948 0.62311869 0.17667656]
 [0.42718837 0.65746913 0.37358236 0.45058577 0.73847523 0.47623488
  0.24948659 0.28334044 0.86944022 0.3431755 ]]

Subtract the mean of each row of the said matrix:

[[ 5.43745140e-02 -1.75738808e-01  1.99408531e-01 -2.02686626e-01
   1.07565533e-02  1.05926866e-01  2.25373831e-01 -1.45517068e-01
  -4.27993438e-02 -2.90984495e-02]
 [ 1.59108936e-01  3.13221664e-01  3.30716724e-01 -3.44341980e-01
  -2.26816173e-01 -2.39067596e-01 -3.78259740e-01 -1.48978885e-01
   2.73282648e-01  2.61134401e-01]
 [-2.60840699e-04 -9

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [24]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

# Slow version

np.diag(np.dot(A, B))

# Fast version

np.sum(A * B.T, axis=1)

# Faster version

np.einsum("ij,ji->i", A, B)

array([1.63840441, 1.95351531, 1.29560649, 0.8163258 , 1.46876283])

# 13.How to find the most frequent value in an array?

In [23]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 4 3 0 2 4 3 4 4 4 0 4 5 7 6 7 9 4 9 7 1 0 0 0 4 6 8 4 2 7 4 9 2 0 9 2 4
 1 5 6]
Most frequent value in the above array:
4


# 14.How to get the n largest values of an array

In [22]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [20]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
